### ISSUE TITLE
Hide notification

### ISSUE THREAD

**Issue by beroal** [fwenzel/copy-url#13]
How do I hide the notification that copying is successful? I don't need it.

BTW, when is it needed? Copying may be unsuccessful?

**Comment by fwenzel** [comment]
Good point! I can look into that and at the very least make it a setting.

**Comment by fwenzel** [comment]
And you're right I don't think there's a scenario where this could fail, since it falls back to window.location.

The URL it displays is the one it found, which may not be the same as `window.location` but could as well be (and is often likely to be) a canonical URL defined in a meta tag.

For an example, go here: http://www.amazon.com/gp/product/B00QH2KHH6/ref=s9_qpp_gw_d99_g193_i5_r?ie=UTF8&fpl=fresh&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=desktop-3&pf_rd_r=0Y0X2EQ3MWP4WTE7JMYW&pf_rd_t=36701&pf_rd_p=2437869462&pf_rd_i=desktop

Then:
- use copy url and note the dramatic difference in what is copied vs. what your window says.
- view source and search for "canonical" to see where this comes from.

**Comment by beroal** [comment]
> use copy url and note the dramatic difference in what is copied vs. what your window says.
Okay. As long as the content on both URLs is the same, it's good for me.

**Comment by fwenzel** [comment]
There was another request for this here: https://addons.mozilla.org/en-US/firefox/addon/copy-url-252534/reviews/808384/reply

Sounds like it's time to make this happen!
