### ISSUE TITLE
a copied URL points to the main page instead of a subpage

### ISSUE THREAD

**Issue by beroal** [fwenzel/copy-url#14]
Why [this URL](https://espora.social/tags/feature) is not copied properly? I don't see any
'link rel="canonical"' inside the webpage.

**Comment by fwenzel** [comment]
Hm turns out their site has this:

`<meta property="og:url" content="https://espora.social/" />`

which is Facebook opengraph metadata. Sharing this on FB does also not work then, I figure. Though I'll read up on the opengraph format to ensure I did not implement this wrong.

Thank you for the report (and sorry for the delay!)

**Comment by fwenzel** [comment]
Yeah I am quite certain they are using Opengraph wrong: http://opengraphprotocol.org/

> og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".

**Comment by beroal** [comment]
Thank you for your reply. I hear about OpenGraph for the first time. I already have created [an issue for their platform](https://github.com/diaspora/diaspora/issues/6840).

**Comment by fwenzel** [comment]
Closing this for now because it appears to be an implementation error on the site.
